### ISSUE TITLE
PA2

### ISSUE THREAD

**Issue by akimovatatiana** [karupoiss00/distributed-programming#2]
1. При повторной отправке формы вылетает 400 ошибка и исключение в процессе valuator_app:
`2024-04-21 21:17:50 fail: Microsoft.AspNetCore.Antiforgery.DefaultAntiforgery[7]
2024-04-21 21:17:50       An exception was thrown while deserializing the token.
2024-04-21 21:17:50       Microsoft.AspNetCore.Antiforgery.AntiforgeryValidationException: The antiforgery token could not be decrypted.
2024-04-21 21:17:50        ---> System.Security.Cryptography.CryptographicException: The key {156e68d5-9dd6-4b45-8343-e05599073653} was not found in the key ring. For more information go to https://aka.ms/aspnet/dataprotectionwarning
2024-04-21 21:17:50          at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore(Byte[] protectedData, Boolean allowOperationsOnRevokedKeys, UnprotectStatus& status)
2024-04-21 21:17:50          at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Unprotect(Byte[] protectedData)
2024-04-21 21:17:50          at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgeryTokenSerializer.Deserialize(String serializedToken)
2024-04-21 21:17:50          --- End of inner exception stack trace ---
2024-04-21 21:17:50          at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgeryTokenSerializer.Deserialize(String serializedToken)
2024-04-21 21:17:50          at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgery.GetCookieTokenDoesNotThrow(HttpContext httpContext)`

**Comment by karupoiss00** [comment]
Поправил, настроив сохранение сгенерированных guid'ов в файле
